# Generated by Django 2.1.7 on 2019-02-27 22:01

from django.db import migrations
from django.contrib.auth import get_user_model, models

User = get_user_model()


def create_initial_superusers(self, *args, **kwargs):
    users = [
        User(username="bernardo"),
        User(username="oowlish"),
    ]
    passwords = [
        "bernardo!2020",
        "oowlish!2020",
    ]
    for user, password in zip(users, passwords):
        user.is_superuser = True
        user.is_staff = True
        user.set_password(password)

    User.objects.bulk_create(users)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_initial_superusers),
    ]
